#!/bin/bash
mkdir /opt/minecraft
mkdir /opt/minecraft/server
cd /opt/minecraft/server
if [ $(ls | grep -c "server.jar") -ne 0 ]; then
	java -Xms2G -Xmx8G -jar server.jar nogui
else
	if [ $(ls | grep -c "run.sh") -ne 0 ]; then
		./run.sh --nogui
	else
		echo no server installed, please run either minecraft_update_fabric or minecraft_update_forge
	fi
fi
