#!/bin/bash
systemctl --user stop minecraft
MINECRAFT_VERSION=${1:-"unknown"}
FABRIC_VERSION=${2:-"unknown"}
RCON_PASSWORD=${2:-"unknown"}
if [ "unknown" == "${MINECRAFT_VERSION}" ]; then
	read -e -p "enter minecraft version:" MINECRAFT_VERSION
fi
if [ "unknown" == "${FABRIC_VERSION}" ]; then
	read -e -p "enter fabric version:" FABRIC_VERSION
fi
if [ "unknown" == "${RCON_PASSWORD}" ]; then
	read -e -p "enter rcon password:" RCON_PASSWORD
fi
mkdir /opt/minecraft
mkdir /opt/minecraft/server
cd /opt/minecraft

if [ "${FABRIC_VERSION}" == "latest" ]; then
	curl -o maven-metadata.xml https://maven.fabricmc.net/net/fabricmc/fabric-installer/maven-metadata.xml
	FABRIC_VERSION=$(cat maven-metadata.xml | grep -oP '(?<=<release>)(?:(?!</release>).)*')
	rm maven-metadata.xml
fi

echo ${MINECRAFT_VERSION} ${FABRIC_VERSION}

if [ $(curl https://maven.fabricmc.net/net/fabricmc/fabric-installer/${FABRIC_VERSION}/fabric-installer-${FABRIC_VERSION}.jar | grep -c "404 Not Found") -ne 0 ]; then
echo fabric version is invalid
exit
fi

mkdir server.old

cp server/* server.old -Rf

rm server/* -Rf

cp server.old/server.properties		server/server.properties.old
cp server.old/mods			server/mods -Rf
cp server.old/banned-ips.json		server/banned-ips.json
cp server.old/banned-players.json	server/banned-players.json
cp server.old/ops.json			server/ops.json
cp server.old/whitelist.json		server/whitelist.json
cp server.old/usercache.json		server/usercache.json
cp server.old/world			server/world -Rf
cp server.old/logs			server/logs -Rf

cd server

curl -o installer.jar https://maven.fabricmc.net/net/fabricmc/fabric-installer/${FABRIC_VERSION}/fabric-installer-${FABRIC_VERSION}.jar

java -jar installer.jar server -mcversion ${MINECRAFT_VERSION} -downloadMinecraft

rm installer.jar

mv server.jar vanilla.jar

mv fabric-server-launch.jar server.jar

echo "serverJar=vanilla.jar" > fabric-server-launcher.properties

java -jar server.jar --nogui

sed -i 's/false/true/g' eula.txt

if [ "$(ls | grep -c server.properties.old)" -ne "0" ]; then
	grep = server.properties.old | while read line
		do
			LINE_VALUE_OLD=$(echo $line | grep -oP '=.*')
			LINE_PROPERTY_OLD=$(echo $line | grep -oP '.*(?==)' )
			echo $LINE_PROPERTY_OLD
			echo $LINE_VALUE_OLD
			sed -i "s/${LINE_PROPERTY_OLD}=.*/${LINE_PROPERTY_OLD}${LINE_VALUE_OLD}/g" server.properties
		done
	rm server.properties.old
fi
sed -i "s/enable-rcon=.*/enable-rcon=true/g" server.properties
sed -i "s/rcon.password=.*/rcon.password=0762h1jnkjdnaksd892q2a8ojd/g" server.properties

read -e -p "add your rcon password to the stop minecraft script? (if you don't do this minecraft might not stop correctly) (yes | no:)" addrconpassword
if [ "yes" == "${addrconpassword}" ]; then
	if [ $(ls /usr/local/bin/minecraft_stop) == $(echo "/usr/local/bin/minecraft_stop") ]; then
		sed -i "s|export RCON_PASSWORD=.*|export RCON_PASSWORD=${RCON_PASSWORD}|g" /usr/local/bin/minecraft_stop
	else
		touch /usr/local/bin/minecraft_stop

		echo '#!/bin/sh

export RCON_PASSWORD=

mcrcon -H 127.0.0.1 -p ${RCON_PASSWORD} -P 25575 stop

while kill -0 $MAINPID 2>/dev/null
do
  sleep 0.5
done
' > /usr/local/bin/minecraft_stop
		sed -i "s|export RCON_PASSWORD=.*|export RCON_PASSWORD=${RCON_PASSWORD}|g" /usr/local/bin/minecraft_stop
		chmod +x /usr/local/bin/minecraft_stop
	fi

fi

echo "server will run in 10 seconds, read the output to find out if it worked correctly and then run stop"
sleep 10

java -jar server.jar --nogui
read -e -p "did server work? (yes | no) :" didserverwork
if [ "yes" == "${didserverwork}" ]; then
cd ..
rm server.old -Rf
else
cd ..
rm server/* -Rf
cp server.old/* server -Rf
rm server.old -Rf
fi
systemctl --user start minecraft
